.dashKaplanMeier_js_metadata <- function() {
deps_metadata <- list(`dash_kaplan_meier` = structure(list(name = "dash_kaplan_meier",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashKaplanMeier.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKaplanMeier",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_kaplan_meier` = structure(list(name = "dash_kaplan_meier",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashKaplanMeier.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKaplanMeier",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_kaplan_meier` = structure(list(name = "dash_kaplan_meier",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_kaplan_meier.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKaplanMeier",
all_files = FALSE), class = "html_dependency"),
`dash_kaplan_meier` = structure(list(name = "dash_kaplan_meier",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_kaplan_meier.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKaplanMeier",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
